---
- hosts: all
  tasks:
    - name: Hello
      debug:
        msg: "TICKET:ddhd {{username}} fdk"
    - name: Sample playbook var (username)
      debug: var=username
  vars:
    username: "DefaultUsernameValue"
  roles:
    - messagebus