---
- hosts: all
  tasks:
    - name: Hello
      debug:
        msg: "Hello!"
    - name: Sample playbook var (username)
      debug:
	msg: "Hello!"
  vars:
    username: "DefaultUsernameValue"
  roles:
    - messagebus